# env:
  # global:
    # travis encrypt GITHUB_USERNAME=....
    # travis encrypt GITHUB_PASSWORD=....
    # travis encrypt GH_TOKEN=....

script: echo "doing nothing here, see deployments below."

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./common-assets/prepare-docs-release.sh
    on:
      branch: root-website
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    email: $GITHUB_EMAIL
    name: $GITHUB_USERNAME
    verbose: true
    keep-history: true
    local-dir: gh-pages-docs
    target_branch: gh-pages
    on:
      branch: root-website

# TODO - enable it when ready to release
# notifications:
#   email:
#     - fdc3-intents@finos.org
#     - announce@finos.org